In [1]:
# in order to select a model we have these known techiques

In [2]:
# 1) use all available data for training and test on same dataset

In [3]:
# 2) split available dataset into training and test sets

In [4]:
# 3) K fold cross validation
# here K fold and cross validation are two techiques but those two have do same behaviour
# the only diffrence is cross validation is the short cut of K fold techique like column transformer 

In [5]:
# in this K fold the original dataset is divied into n_splits
# the output of after n_splits is training_index and testing_index of training and testing sets

In [25]:
# if the original datset is divided into 3 splits
# then we have three splits of our dataset i.e. 1,2,3
# here no of splits = no of iterations
# in first iteration the first split is testing data and the remaining two splits are training data
# in second iteration the second split is testing data and the remaining two splits are training data
# in second iteration the third split is testing data and the remaining two splits are training data
# for example the data is [1,2,3,4,5,6,7,8,9]
# in first iteration the data is [1,2,3,4,5,6] -training included two splits and [7,8,9] - testing includes one split
# in second iteration the data is [1,2,3,7,8,9] and [4,5,6]
# in third iteration the data is [4,5,6,7,8,9] and [1,2,3]
# in every iteration we find the score 
# and then average the score to fing the best score

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [10]:
import numpy as np

In [11]:
from sklearn.datasets import load_digits

In [12]:
digits=load_digits()

In [13]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [16]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\Manikanta\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [17]:
sv=SVC()
sv.fit(x_train,y_train)
sv.score(x_test,y_test)

0.9888888888888889

In [18]:
rf=RandomForestClassifier(n_estimators=10)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.937037037037037

In [19]:
from sklearn.model_selection import KFold

In [40]:
kf=KFold(n_splits=5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [42]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9,10]):
    print(train_index,test_index)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [43]:
def get_score(model,x_trian,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [44]:
from sklearn.model_selection import StratifiedKFold

In [45]:
skf=StratifiedKFold(n_splits=5)
skf

StratifiedKFold(n_splits=5, random_state=None, shuffle=False)

In [46]:
scores_l=[]
scores_svm=[]
scores_rf=[]
for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test))

C:\Users\Manikanta\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Manikanta\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
 

In [47]:
scores_l

[0.9277777777777778,
 0.8666666666666667,
 0.9387186629526463,
 0.935933147632312,
 0.9080779944289693]

In [48]:
scores_svm

[0.9694444444444444,
 0.9472222222222222,
 0.9832869080779945,
 0.9888579387186629,
 0.9415041782729805]

In [49]:
scores_rf

[0.9222222222222223,
 0.8888888888888888,
 0.9554317548746518,
 0.9665738161559888,
 0.9108635097493036]

In [50]:
scores_l=[]
scores_svm=[]
scores_rf=[]
for train_index,test_index in skf.split(digits.data,digits.target):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test))

C:\Users\Manikanta\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Manikanta\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
 

In [51]:
scores_l

[0.9222222222222223,
 0.8694444444444445,
 0.9415041782729805,
 0.9387186629526463,
 0.8969359331476323]

In [52]:
scores_svm

[0.9611111111111111,
 0.9444444444444444,
 0.9832869080779945,
 0.9888579387186629,
 0.9387186629526463]

In [53]:
scores_rf

[0.9305555555555556,
 0.8944444444444445,
 0.9526462395543176,
 0.958217270194986,
 0.9275766016713092]

In [54]:
from sklearn.model_selection import cross_val_score

In [56]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\Manikanta\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Manikanta\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
 

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [57]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [58]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.92777778, 0.91666667, 0.95821727, 0.95821727, 0.9275766 ])

In [61]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target)

array([0.94166667, 0.90555556, 0.94986072, 0.9637883 , 0.91922006])

### exercise

In [62]:
from sklearn.datasets import load_iris

In [63]:
iris=load_iris()

In [64]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [65]:
import pandas as pd

In [66]:
data=pd.DataFrame(iris.data,columns=iris.feature_names)

In [67]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [68]:
data["target"]=iris.target

In [69]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [77]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [78]:
from sklearn.model_selection import cross_val_score

In [79]:
from sklearn.model_selection import StratifiedKFold

In [80]:
skf=StratifiedKFold(n_splits=3)
skf

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [86]:
s_scores=cross_val_score(SVC(),data.drop(columns=["target"]),data.target)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [87]:
r_scores=cross_val_score(RandomForestClassifier(),data.drop(columns=["target"]),data.target)
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [88]:
d_scores=cross_val_score(DecisionTreeClassifier(),data.drop(columns=["target"]),data.target)
d_scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [89]:
np.average(s_scores)

0.9666666666666666

In [90]:
np.average(r_scores)

0.9666666666666668

In [91]:
np.average(d_scores)

0.9600000000000002

In [85]:
# hence RandomForestClassifier is the best model for iris dataset