In [2]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

In [3]:
data=pd.read_csv('C:/Users/Manikanta/Machine learning/Home_prices.csv')

In [4]:
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
data["bedrooms"].isnull().sum()

1

In [6]:
data["bedrooms"]  # this is series

0    3.0
1    4.0
2    NaN
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [7]:
data["bedrooms"].values   # this is array

array([ 3.,  4., nan,  3.,  5.,  6.])

In [8]:
data["bedrooms"].values.mean()

nan

In [9]:
np.nanmean(data["bedrooms"].values)

4.2

In [10]:
data["bedrooms"]=data["bedrooms"].fillna(np.floor(np.nanmean(data["bedrooms"].values)))

In [11]:
# we can also use this
data["bedrooms"]=data["bedrooms"].fillna(np.floor(data["bedrooms"].mean()))

In [12]:
data    # price=m1*area+m2*bedrooms+m3*age+b
        # i.e. is y=m1*x1+m2*x2+m3*x3+b

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
reg=LinearRegression()
reg.fit(data[["area","bedrooms","age"]],data["price"])

LinearRegression()

In [15]:
reg.intercept_  # this is b i.e. intercept in y=m1*x1+m2*x2+m3*x3+b

221323.00186540408

In [16]:
reg.coef_   # these are m1,m2,m3 also known as weights in deep learning

array([  112.06244194, 23388.88007794, -3231.71790863])

In [17]:
reg.predict([[3000,3,40]])

C:\Users\Manikanta\anaconda3\envs\env_deeplearning\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([498408.25158031])

In [18]:
# y_pred=m1*x1+m2*x2+m3*x3+b
y_pred=112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540408
y_pred

498408.2515740241

### exercise

In [40]:
!pip install word2number

In [41]:
import word2number

In [42]:
from word2number import w2n

In [43]:
data=pd.read_csv("C:/Users/Manikanta/Machine learning/Hiring.csv")

In [44]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [45]:
data["experience"]=data["experience"].fillna("zero")  # if we don't fill nan values then it produces error when it comes to word_to_num function

In [46]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [47]:
data["experience"]=data["experience"].apply(lambda x:w2n.word_to_num(x))

In [48]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [49]:
data["test_score(out of 10)"].isnull().sum()

1

In [50]:
import math

In [52]:
data["test_score(out of 10)"].median()

8.0

In [53]:
data["test_score(out of 10)"]=data["test_score(out of 10)"].fillna(math.floor(data["test_score(out of 10)"].median()))

In [54]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [56]:
from sklearn.linear_model import LinearRegression

In [57]:
mreg=LinearRegression()
mreg.fit(data[["experience","test_score(out of 10)","interview_score(out of 10)"]],data["salary($)"])

LinearRegression()

In [58]:
mreg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [59]:
mreg.intercept_

17737.26346433771

In [63]:
mreg.predict([[2,9,6]])

C:\Users\Manikanta\anaconda3\envs\env_deeplearning\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([53205.96797671])

In [67]:
# y_pred=m1x1+m2x2+m3x3+b
y_pred=2812.95487627*2+1845.70596798*9+2205.24017467*6+17737.26346433771
y_pred

53205.967976717715

In [64]:
mreg.predict([[12,10,10]])

C:\Users\Manikanta\anaconda3\envs\env_deeplearning\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([92002.18340611])

In [68]:
y_pred=2812.95487627*12+1845.70596798*10+2205.24017467*10+17737.26346433771
y_pred

92002.1834060777