In [1]:
from numpy import *

In [2]:
arr1=array([[[1,2],[3,4]],[[1,2],[3,4]]])
arr1.shape

(2, 2, 2)

### convert higher dimensional arrays into single dimensional array

In [3]:
arr2=arr1.flatten()

In [4]:
arr2

array([1, 2, 3, 4, 1, 2, 3, 4])

### reshape the array

In [5]:
arr3=arr2.reshape((4,2),order="C")  # C means row wise array reshaped

In [6]:
arr3

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [25]:
arr5=arr2.reshape((-1,2),order="C") # here -1 indicates as much as the rows need to fulfill two columns

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [26]:
arr6=arr2.reshape((4,-1),order="C") # here -1 indicates as much as the columns need to fulfill 4 rows
arr6

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [16]:
arr4=arr2.reshape((4,2),order="F") # F means column wise array reshaped
arr4

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

# matrix

In [17]:
m1=matrix("1 2 3;1 2 3;1 2 3")
m1

matrix([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [18]:
print(diagonal(m1))

[1 2 3]


In [19]:
m1.min() # this works for both single and higher dimensional arrays,matrix

1

In [20]:
min(arr2) # this works for single dimension array

1

In [21]:
import numpy as np # well this works
np.min(arr3)

1

In [22]:
m2=matrix("1 2 3;1 2 3;1 2 3")
m2

matrix([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [23]:
m1+m2

matrix([[2, 4, 6],
        [2, 4, 6],
        [2, 4, 6]])

In [24]:
m1*m2

matrix([[ 6, 12, 18],
        [ 6, 12, 18],
        [ 6, 12, 18]])

In [28]:
m1

matrix([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [29]:
m1.transpose()

matrix([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [37]:
from numpy import linalg as lg

In [38]:
lg.det(m1)

0.0

In [42]:
lg.inv(m1)

LinAlgError: Singular matrix

In [45]:
lg.eig(m2)

(array([ 6.00000000e+00,  4.03541664e-17, -2.96106259e-16]),
 matrix([[ 0.57735027, -0.06824394,  0.91960957],
         [ 0.57735027, -0.81946204, -0.39007323],
         [ 0.57735027,  0.569056  , -0.0464877 ]]))